name: Build and Deploy

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Commit lint ✨
        uses: wagoid/commitlint-github-action@v5

      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup PNPM
        uses: pnpm/action-setup@master
        with:
          version: latest

      - name: Install and Build 🔧
        run: |
          pnpm install
          pnpm run build

      - name: Lint ✨
        run: pnpm test.lint

      - name: Deploy 🚀
        if: github.ref == 'refs/heads/master' && github.event.repository.fork == false
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: _site # The folder the action should deploy.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
